"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Vinext client navigation is unstable for these routes. */
/* eslint-disable jsx-a11y/no-static-element-interactions, jsx-a11y/no-noninteractive-element-interactions -- Backdrop click closes the modal; the form stops propagation. */

import { FormEvent, useMemo, useState } from "react";
import type { LineConnection } from "../line";

type Status = "received" | "checking" | "repairing" | "completed";
type Job = { id:string; customerName:string; phone:string; deviceType:string; deviceModel:string; symptoms:string[]; status:Status; priority:"urgent"|"normal"|"low"; estimatedMin:number|null; estimatedMax:number|null; finalPrice:number|null; paymentStatus:"unpaid"|"pending"|"paid"; adminNote:string|null; updatedAt:number; history:Array<{status:string;note:string|null;createdAt:number}> };
type Payment = { id:string; repairId:string; amount:number; method:"qr"|"bank"; originalName:string; contentType:string; status:"pending"|"paid"|"rejected"; createdAt:number; reviewedAt:number|null };
type Props = { admin:{displayName:string;email:string}; initialJobs:Job[]; initialPayments:Payment[]; lineConnection:LineConnection };

const columns = [
  { id:"received", icon:"📥", title:"รอรับเรื่อง" }, { id:"checking", icon:"🔎", title:"กำลังตรวจ/รออะไหล่" },
  { id:"repairing", icon:"🔧", title:"กำลังซ่อม" }, { id:"completed", icon:"✅", title:"เสร็จสิ้น" },
] as const;

export default function AdminDashboard({ admin, initialJobs, initialPayments, lineConnection }: Props) {
  const [jobs,setJobs]=useState(initialJobs); const [payments,setPayments]=useState(initialPayments); const [query,setQuery]=useState(""); const [tab,setTab]=useState<"queue"|"payments"|"reports"|"settings">("queue");
  const [editing,setEditing]=useState<Job|null>(null); const [saving,setSaving]=useState(false);
  const [lineTest,setLineTest]=useState<"idle"|"sending"|"sent"|"failed">("idle");
  const visible=useMemo(()=>jobs.filter(j=>`${j.id} ${j.customerName} ${j.phone} ${j.deviceModel}`.toLowerCase().includes(query.toLowerCase())),[jobs,query]);
  const revenue=jobs.filter(j=>j.paymentStatus==="paid").reduce((sum,j)=>sum+(j.finalPrice??0),0);
  const complete=jobs.filter(j=>j.status==="completed").length; const paid=jobs.filter(j=>j.paymentStatus==="paid").length;

  async function advance(job:Job){const index=columns.findIndex(c=>c.id===job.status);if(index===columns.length-1)return;const status=columns[index+1].id;const response=await fetch(`/api/repairs/${encodeURIComponent(job.id)}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,note:`อัปเดตโดย ${admin.displayName}`})});if(response.ok)setJobs(current=>current.map(item=>item.id===job.id?{...item,status}:item));}
  async function saveDetails(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;setSaving(true);const form=new FormData(event.currentTarget);const response=await fetch(`/api/repairs/${encodeURIComponent(editing.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});if(response.ok){const data=await response.json() as {repair:Job};setJobs(current=>current.map(item=>item.id===editing.id?data.repair:item));setEditing(null);}setSaving(false);}
  async function testLine(){setLineTest("sending");const response=await fetch("/api/admin/line/test",{method:"POST"});setLineTest(response.ok?"sent":"failed");}
  async function reviewPayment(id:string,status:"paid"|"rejected"){const response=await fetch(`/api/admin/payments/${encodeURIComponent(id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(response.ok){const data=await response.json() as {payment:Payment};setPayments(current=>current.map(item=>item.id===id?data.payment:item));const payment=payments.find(item=>item.id===id);if(payment)setJobs(current=>current.map(job=>job.id===payment.repairId?{...job,paymentStatus:status==="paid"?"paid":"unpaid"}:job));}}

  return <main className="repair-dashboard">
    <div className={`line-connection-banner ${lineConnection.connected ? "connected" : "disconnected"}`}>
      <span>LINE</span><div><strong>{lineConnection.connected ? `เชื่อมต่อ ${lineConnection.displayName ?? "LINE Official Account"} แล้ว` : "ยังเชื่อมต่อ LINE ไม่สำเร็จ"}</strong><small>{lineTest==="sent"?"ส่งข้อความทดสอบสำเร็จแล้ว":lineTest==="failed"?"ส่งไม่สำเร็จ กรุณาเพิ่ม Official Account เป็นเพื่อน":lineConnection.connected&&!lineConnection.recipientConfigured?"Channel Token ใช้งานได้ • รอ User ID ผู้รับข้อความ":lineConnection.recipientConfigured?"พร้อมส่งข้อความทดสอบ":lineConnection.error??"กรุณาตรวจสอบ Channel access token"}</small></div>{lineConnection.connected&&lineConnection.recipientConfigured&&<button type="button" disabled={lineTest==="sending"} onClick={testLine}>{lineTest==="sending"?"กำลังส่ง...":"ส่งทดสอบ"}</button>}
    </div>
    <aside className="repair-sidebar"><a className="online-brand" href="/"><span className="online-logo">🔧</span><strong>FixIt Online</strong></a><nav>
      <button className={tab==="reports"?"selected":""} onClick={()=>setTab("reports")}>📊 <span>รายงานภาพรวม</span></button>
      <button className={tab==="queue"?"selected":""} onClick={()=>setTab("queue")}>📋 <span>จัดการงานซ่อม</span></button>
      <button className={tab==="payments"?"selected":""} onClick={()=>setTab("payments")}>💳 <span>ตรวจสอบการชำระเงิน</span></button>
      <button className={tab==="settings"?"selected":""} onClick={()=>setTab("settings")}>⚙️ <span>ตั้งค่าระบบ</span></button>
    </nav><form action="/api/admin/logout" method="post"><button type="submit">↪ <span>ออกจากระบบ</span></button></form></aside>
    <section className="repair-workspace"><header className="admin-topbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหารหัสงาน ลูกค้า เบอร์โทร หรืออุปกรณ์" aria-label="ค้นหางานซ่อม" /></label><div><i>◎</i><p><strong>{admin.displayName}</strong><small>{admin.email}</small></p></div></header>
      {tab==="queue"&&<><div className="board-heading"><div><p>ศูนย์ควบคุมงานซ่อม</p><h1>จัดการงานซ่อม <span>(Repair Queue)</span></h1><small>แก้ราคา หมายเหตุ การชำระเงิน และอัปเดตสถานะให้ลูกค้าติดตามได้ทันที</small></div><span className="line-online">▣ รอตั้งค่าการแจ้งเตือน LINE</span></div><section className="repair-board">{columns.map(column=>{const items=visible.filter(j=>j.status===column.id);return <section className={`board-column ${column.id}`} key={column.id}><header><h2>{column.icon} {column.title}</h2><span>{items.length}</span></header><div>{items.map(job=><article className="repair-job-card" key={job.id}><header><a href={`/repair/status/${encodeURIComponent(job.id)}`}>#{job.id}</a><span className={job.priority}>{job.priority==="urgent"?"ด่วนที่สุด":job.priority==="low"?"ทั่วไป":"ปกติ"}</span></header><h3>{job.deviceType.includes("โทรศัพท์")?"📱":"💻"} {job.deviceModel}</h3><p>ลูกค้า: {job.customerName}</p><div className="job-symptom">🛠 {job.symptoms.join(", ")}</div>{job.adminNote&&<p className="job-note">📝 {job.adminNote}</p>}<footer><span className={`payment-chip ${job.paymentStatus}`}>{job.paymentStatus==="paid"?"ชำระแล้ว":job.paymentStatus==="pending"?"รอตรวจสอบ":"ยังไม่ชำระ"}</span><strong>{job.finalPrice?`${job.finalPrice.toLocaleString()} บาท`:job.estimatedMin?`${job.estimatedMin.toLocaleString()}${job.estimatedMax&&job.estimatedMax!==job.estimatedMin?` - ${job.estimatedMax.toLocaleString()}`:""} บาท`:"รอประเมิน"}</strong></footer><div className="job-actions"><button onClick={()=>setEditing(job)}>แก้ไข</button>{column.id!=="completed"&&<button onClick={()=>advance(job)}>ขั้นตอนถัดไป →</button>}</div></article>)}</div></section>})}</section></>}
      {tab==="reports"&&<section className="admin-section"><div className="section-title"><p>รายงานร้าน</p><h1>ภาพรวมการดำเนินงาน</h1></div><div className="report-grid"><article><span>📋</span><small>งานทั้งหมด</small><strong>{jobs.length}</strong></article><article><span>🔧</span><small>กำลังดำเนินการ</small><strong>{jobs.length-complete}</strong></article><article><span>✅</span><small>งานเสร็จสิ้น</small><strong>{complete}</strong></article><article><span>฿</span><small>รายรับที่ยืนยันแล้ว</small><strong>{revenue.toLocaleString()} บาท</strong></article></div><div className="report-panel"><h2>สรุปการชำระเงิน</h2><div><span>ชำระแล้ว <b>{paid} งาน</b></span><span>รอตรวจสอบ <b>{jobs.filter(j=>j.paymentStatus==="pending").length} งาน</b></span><span>ยังไม่ชำระ <b>{jobs.filter(j=>j.paymentStatus==="unpaid").length} งาน</b></span></div></div></section>}
      {tab==="payments"&&<section className="admin-section"><div className="section-title"><p>หลักฐานการชำระเงิน</p><h1>ตรวจสอบสลิปจากลูกค้า</h1></div><div className="payment-review-list">{payments.length===0?<p className="empty-admin-state">ยังไม่มีหลักฐานการชำระเงิน</p>:payments.map(payment=>{const job=jobs.find(item=>item.id===payment.repairId);return <article key={payment.id}><div><small>#{payment.repairId} · {new Date(payment.createdAt*1000).toLocaleString("th-TH")}</small><h2>{job?.customerName??"ลูกค้า"} · {payment.amount.toLocaleString()} บาท</h2><p>{job?.deviceModel} · {payment.method==="qr"?"พร้อมเพย์":"โอนธนาคาร"}</p></div><span className={`payment-review-status ${payment.status}`}>{payment.status==="pending"?"รอตรวจสอบ":payment.status==="paid"?"อนุมัติแล้ว":"ปฏิเสธแล้ว"}</span><div className="payment-review-actions"><a href={`/api/admin/payments/${encodeURIComponent(payment.id)}/slip`} target="_blank" rel="noreferrer">เปิดสลิป</a>{payment.status==="pending"&&<><button onClick={()=>reviewPayment(payment.id,"rejected")}>ปฏิเสธ</button><button className="approve" onClick={()=>reviewPayment(payment.id,"paid")}>อนุมัติ</button></>}</div></article>})}</div></section>}
      {tab==="settings"&&<section className="admin-section settings-grid"><div><div className="section-title"><p>ความปลอดภัย</p><h1>เปลี่ยนรหัสผ่านแอดมิน</h1></div><form className="settings-card" action="/api/admin/change-password" method="post"><label>รหัสผ่านปัจจุบัน<input required type="password" name="currentPassword" autoComplete="current-password" /></label><label>รหัสผ่านใหม่<input required type="password" name="newPassword" minLength={12} autoComplete="new-password" /></label><label>ยืนยันรหัสผ่านใหม่<input required type="password" name="confirmPassword" minLength={12} autoComplete="new-password" /></label><button className="button button-primary" type="submit">เปลี่ยนรหัสผ่าน</button><small>เมื่อเปลี่ยนสำเร็จ ระบบจะออกจากระบบทุกอุปกรณ์</small></form></div><div><div className="section-title"><p>การเชื่อมต่อ</p><h1>LINE แจ้งเตือน</h1></div><div className="settings-card integration-card"><span>LINE</span><h2>ยังไม่ได้เชื่อมต่อ</h2><p>โครงสร้างพร้อมใช้งาน แต่ต้องเพิ่ม Channel access token และผู้รับข้อความของร้านก่อนส่งจริง</p><b>รอข้อมูล LINE Official Account</b></div></div></section>}
    </section>
    {editing&&<div className="editor-backdrop" onMouseDown={()=>setEditing(null)}><form className="job-editor" onSubmit={saveDetails} onMouseDown={e=>e.stopPropagation()}><header><div><small>แก้ไขงานซ่อม</small><h2>#{editing.id}</h2></div><button type="button" onClick={()=>setEditing(null)}>×</button></header><label>ความเร่งด่วน<select name="priority" defaultValue={editing.priority}><option value="urgent">ด่วนที่สุด</option><option value="normal">ปกติ</option><option value="low">ทั่วไป</option></select></label><div className="editor-row"><label>ราคาประเมินต่ำสุด<input name="estimatedMin" type="number" min="0" defaultValue={editing.estimatedMin??""} /></label><label>ราคาประเมินสูงสุด<input name="estimatedMax" type="number" min="0" defaultValue={editing.estimatedMax??""} /></label></div><label>ราคาสุทธิ<input name="finalPrice" type="number" min="0" defaultValue={editing.finalPrice??""} /></label><label>สถานะชำระเงิน<select name="paymentStatus" defaultValue={editing.paymentStatus}><option value="unpaid">ยังไม่ชำระ</option><option value="pending">รอตรวจสอบ</option><option value="paid">ชำระแล้ว</option></select></label><label>หมายเหตุภายใน<textarea name="adminNote" defaultValue={editing.adminNote??""} /></label><button className="button button-primary full" disabled={saving}>{saving?"กำลังบันทึก...":"บันทึกข้อมูล"}</button></form></div>}
  </main>;
}
